name: Deploy to Google Play

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Check out
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update auth secrets
        env:
          AUTH_SECRET_IV: ${{ secrets.AUTH_SECRET_IV }}
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
        run: |
          cat <<EOF > local.properties
          AUTH_SECRET_IV:"$AUTH_SECRET_IV"
          AUTH_SECRET_KEY:"$AUTH_SECRET_KEY"
          EOF

      - name: Create BuildKonfig
        run: ./gradlew generateBuildKonfig

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: composeApp/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: composeApp/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Setup Authorization with Google Play
        run: echo '${{ secrets.GOOGLE_PLAY_AUTH_JSON }}' > service-account.json

      - name: Deploy Bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service-account.json
          packageName: org.thejohnsondev.vault
          releaseFiles: composeApp/build/outputs/bundle/release/PassGuard-release.aab
          track: internal
          status: completed
          whatsNewDirectory: whatsNew