name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update auth secrets
        env:
          AUTH_SECRET_IV: ${{ secrets.AUTH_SECRET_IV }}
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
        run: |
          cat <<EOF > local.properties
          AUTH_SECRET_IV:"$AUTH_SECRET_IV"
          AUTH_SECRET_KEY:"$AUTH_SECRET_KEY"
          EOF

      - name: Create BuildKonfig
        run: ./gradlew generateBuildKonfig

  build:
    needs: prepare-environment
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app
        run: ./gradlew assembleDebug :core:common:assembleAndroidTest

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          ./gradlew :core:common:test
          ./gradlew :core:network:test
          ./gradlew :feature:auth:domain:test
          ./gradlew :feature:vault:domain:test

      - name: Run Android tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: android-device.yml:android-pixel-4
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_TEST_LAB_SERVICE_ACCOUNT }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            core/common/build/test-results/**/*.xml
            core/network/build/test-results/**/*.xml
            feature/auth/domain/build/test-results/**/*.xml